[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[notify]
icon_info  = ""
icon_warn  = ""
icon_error = ""

[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = []

[which]
separator = " ➜ "

# https://github.com/Mellbourn/lsColorsToToml
[filetype]
rules = [
  { name = "*", is = "block", fg = "#b58900", bg = "#eee8d5", bold = true },
  { name = "*", is = "char", fg = "#b58900", bg = "#eee8d5", bold = true },
  { name = "*/", fg = "#268bd2", bold = true },
  { name = "*", is = "exec", fg = "#859900", bold = true },
  { name = "*", is = "link", fg = "#2aa198", bold = true },
  { name = "*", is = "orphan", fg = "#dc322f", bg = "#eee8d5", bold = true },
  { name = "*", is = "fifo", fg = "#b58900", bg = "#eee8d5", bold = true },
  { name = "*", is = "sock", fg = "#d33682", bg = "#eee8d5", bold = true },
  { name = "*", is = "sticky" },
  { name = "*.1", fg = "#839496" },
  { name = "*.a", fg = "#839496" },
  { name = "*.c", fg = "#839496" },
  { name = "*.d", fg = "#839496" },
  { name = "*.h", fg = "#839496" },
  { name = "*.m", fg = "#839496" },
  { name = "*.o", fg = "#586e75" },
  { name = "*.p", fg = "#839496" },
  { name = "*.r", fg = "#839496" },
  { name = "*.t", fg = "#839496" },
  { name = "*.v", fg = "#839496" },
  { name = "*.z", fg = "#dc322f", bold = true },
  { name = "*.7z", fg = "#dc322f", bold = true },
  { name = "*.ai", fg = "#d33682" },
  { name = "*.as", fg = "#839496" },
  { name = "*.bc", fg = "#586e75" },
  { name = "*.bz", fg = "#dc322f", bold = true },
  { name = "*.cc", fg = "#839496" },
  { name = "*.cp", fg = "#839496" },
  { name = "*.cr", fg = "#839496" },
  { name = "*.cs", fg = "#839496" },
  { name = "*.db", fg = "#dc322f", bold = true },
  { name = "*.di", fg = "#839496" },
  { name = "*.el", fg = "#839496" },
  { name = "*.ex", fg = "#839496" },
  { name = "*.fs", fg = "#839496" },
  { name = "*.go", fg = "#839496" },
  { name = "*.gv", fg = "#839496" },
  { name = "*.gz", fg = "#dc322f", bold = true },
  { name = "*.ha", fg = "#839496" },
  { name = "*.hh", fg = "#839496" },
  { name = "*.hi", fg = "#586e75" },
  { name = "*.hs", fg = "#839496" },
  { name = "*.jl", fg = "#839496" },
  { name = "*.js", fg = "#839496" },
  { name = "*.ko", fg = "#839496" },
  { name = "*.kt", fg = "#839496" },
  { name = "*.la", fg = "#586e75" },
  { name = "*.ll", fg = "#839496" },
  { name = "*.lo", fg = "#586e75" },
  { name = "*.ma", fg = "#d33682" },
  { name = "*.mb", fg = "#d33682" },
  { name = "*.md", fg = "#839496" },
  { name = "*.mk", fg = "#839496" },
  { name = "*.ml", fg = "#839496" },
  { name = "*.mn", fg = "#839496" },
  { name = "*.nb", fg = "#839496" },
  { name = "*.nu", fg = "#839496" },
  { name = "*.pl", fg = "#839496" },
  { name = "*.pm", fg = "#839496" },
  { name = "*.pp", fg = "#839496" },
  { name = "*.ps", fg = "#cb4b16" },
  { name = "*.py", fg = "#839496" },
  { name = "*.rb", fg = "#839496" },
  { name = "*.rm", fg = "#d33682", bold = true },
  { name = "*.rs", fg = "#839496" },
  { name = "*.sh", fg = "#839496" },
  { name = "*.so", fg = "#839496" },
  { name = "*.td", fg = "#839496" },
  { name = "*.ts", fg = "#839496" },
  { name = "*.ui", fg = "#839496" },
  { name = "*.vb", fg = "#839496" },
  { name = "*.wv", fg = "#2aa198" },
  { name = "*.xz", fg = "#dc322f", bold = true },
  { name = "*FAQ", fg = "#839496" },
  { name = "*.3ds", fg = "#d33682" },
  { name = "*.3fr", fg = "#d33682" },
  { name = "*.3mf", fg = "#d33682" },
  { name = "*.adb", fg = "#839496" },
  { name = "*.ads", fg = "#839496" },
  { name = "*.aif", fg = "#2aa198" },
  { name = "*.amf", fg = "#d33682" },
  { name = "*.ape", fg = "#2aa198" },
  { name = "*.apk", fg = "#dc322f", bold = true },
  { name = "*.ari", fg = "#d33682" },
  { name = "*.arj", fg = "#dc322f", bold = true },
  { name = "*.arw", fg = "#d33682" },
  { name = "*.asa", fg = "#839496" },
  { name = "*.asm", fg = "#839496" },
  { name = "*.aux", fg = "#586e75" },
  { name = "*.avi", fg = "#d33682", bold = true },
  { name = "*.awk", fg = "#839496" },
  { name = "*.bag", fg = "#dc322f", bold = true },
  { name = "*.bak", fg = "#586e75" },
  { name = "*.bat", fg = "#839496" },
  { name = "*.bay", fg = "#d33682" },
  { name = "*.bbl", fg = "#586e75" },
  { name = "*.bcf", fg = "#586e75" },
  { name = "*.bib", fg = "#839496" },
  { name = "*.bin", fg = "#dc322f", bold = true },
  { name = "*.blg", fg = "#586e75" },
  { name = "*.bmp", fg = "#d33682" },
  { name = "*.bsh", fg = "#839496" },
  { name = "*.bst", fg = "#839496" },
  { name = "*.bz2", fg = "#dc322f", bold = true },
  { name = "*.c++", fg = "#839496" },
  { name = "*.cap", fg = "#d33682" },
  { name = "*.cfg", fg = "#839496" },
  { name = "*.cgi", fg = "#839496" },
  { name = "*.clj", fg = "#839496" },
  { name = "*.com", fg = "#839496" },
  { name = "*.cpp", fg = "#839496" },
  { name = "*.cr2", fg = "#d33682" },
  { name = "*.cr3", fg = "#d33682" },
  { name = "*.crw", fg = "#d33682" },
  { name = "*.css", fg = "#839496" },
  { name = "*.csv", fg = "#839496" },
  { name = "*.csx", fg = "#839496" },
  { name = "*.cxx", fg = "#839496" },
  { name = "*.dae", fg = "#d33682" },
  { name = "*.dcr", fg = "#d33682" },
  { name = "*.dcs", fg = "#d33682" },
  { name = "*.deb", fg = "#dc322f", bold = true },
  { name = "*.def", fg = "#839496" },
  { name = "*.dll", fg = "#839496" },
  { name = "*.dmg", fg = "#dc322f", bold = true },
  { name = "*.dng", fg = "#d33682" },
  { name = "*.doc", fg = "#cb4b16" },
  { name = "*.dot", fg = "#839496" },
  { name = "*.dox", fg = "#839496" },
  { name = "*.dpr", fg = "#839496" },
  { name = "*.drf", fg = "#d33682" },
  { name = "*.dxf", fg = "#d33682" },
  { name = "*.eip", fg = "#d33682" },
  { name = "*.elc", fg = "#839496" },
  { name = "*.elm", fg = "#839496" },
  { name = "*.epp", fg = "#839496" },
  { name = "*.eps", fg = "#d33682" },
  { name = "*.erf", fg = "#d33682" },
  { name = "*.erl", fg = "#839496" },
  { name = "*.exe", fg = "#839496" },
  { name = "*.exr", fg = "#d33682" },
  { name = "*.exs", fg = "#839496" },
  { name = "*.fbx", fg = "#d33682" },
  { name = "*.fff", fg = "#d33682" },
  { name = "*.fls", fg = "#586e75" },
  { name = "*.flv", fg = "#d33682", bold = true },
  { name = "*.fnt", fg = "#6c71c4" },
  { name = "*.fon", fg = "#6c71c4" },
  { name = "*.fsi", fg = "#839496" },
  { name = "*.fsx", fg = "#839496" },
  { name = "*.gif", fg = "#d33682" },
  { name = "*.git", fg = "#586e75" },
  { name = "*.gpr", fg = "#d33682" },
  { name = "*.gvy", fg = "#839496" },
  { name = "*.h++", fg = "#839496" },
  { name = "*.hda", fg = "#d33682" },
  { name = "*.hip", fg = "#d33682" },
  { name = "*.hpp", fg = "#839496" },
  { name = "*.htc", fg = "#839496" },
  { name = "*.htm", fg = "#839496" },
  { name = "*.hxx", fg = "#839496" },
  { name = "*.ico", fg = "#d33682" },
  { name = "*.ics", fg = "#cb4b16" },
  { name = "*.idx", fg = "#586e75" },
  { name = "*.igs", fg = "#d33682" },
  { name = "*.iiq", fg = "#d33682" },
  { name = "*.ilg", fg = "#586e75" },
  { name = "*.img", fg = "#dc322f", bold = true },
  { name = "*.inc", fg = "#839496" },
  { name = "*.ind", fg = "#586e75" },
  { name = "*.ini", fg = "#839496" },
  { name = "*.inl", fg = "#839496" },
  { name = "*.ino", fg = "#839496" },
  { name = "*.ipp", fg = "#839496" },
  { name = "*.iso", fg = "#dc322f", bold = true },
  { name = "*.jar", fg = "#dc322f", bold = true },
  { name = "*.jpg", fg = "#d33682" },
  { name = "*.jsx", fg = "#839496" },
  { name = "*.jxl", fg = "#d33682" },
  { name = "*.k25", fg = "#d33682" },
  { name = "*.kdc", fg = "#d33682" },
  { name = "*.kex", fg = "#cb4b16" },
  { name = "*.kra", fg = "#d33682" },
  { name = "*.kts", fg = "#839496" },
  { name = "*.log", fg = "#586e75" },
  { name = "*.ltx", fg = "#839496" },
  { name = "*.lua", fg = "#839496" },
  { name = "*.m3u", fg = "#2aa198" },
  { name = "*.m4a", fg = "#2aa198" },
  { name = "*.m4v", fg = "#d33682", bold = true },
  { name = "*.mdc", fg = "#d33682" },
  { name = "*.mef", fg = "#d33682" },
  { name = "*.mid", fg = "#2aa198" },
  { name = "*.mir", fg = "#839496" },
  { name = "*.mkv", fg = "#d33682", bold = true },
  { name = "*.mli", fg = "#839496" },
  { name = "*.mos", fg = "#d33682" },
  { name = "*.mov", fg = "#d33682", bold = true },
  { name = "*.mp3", fg = "#2aa198" },
  { name = "*.mp4", fg = "#d33682", bold = true },
  { name = "*.mpg", fg = "#d33682", bold = true },
  { name = "*.mrw", fg = "#d33682" },
  { name = "*.msi", fg = "#dc322f", bold = true },
  { name = "*.mtl", fg = "#d33682" },
  { name = "*.nef", fg = "#d33682" },
  { name = "*.nim", fg = "#839496" },
  { name = "*.nix", fg = "#839496" },
  { name = "*.nrw", fg = "#d33682" },
  { name = "*.obj", fg = "#d33682" },
  { name = "*.obm", fg = "#d33682" },
  { name = "*.odp", fg = "#cb4b16" },
  { name = "*.ods", fg = "#cb4b16" },
  { name = "*.odt", fg = "#cb4b16" },
  { name = "*.ogg", fg = "#2aa198" },
  { name = "*.ogv", fg = "#d33682", bold = true },
  { name = "*.orf", fg = "#d33682" },
  { name = "*.org", fg = "#839496" },
  { name = "*.otf", fg = "#6c71c4" },
  { name = "*.otl", fg = "#d33682" },
  { name = "*.out", fg = "#586e75" },
  { name = "*.pas", fg = "#839496" },
  { name = "*.pbm", fg = "#d33682" },
  { name = "*.pcx", fg = "#d33682" },
  { name = "*.pdf", fg = "#cb4b16" },
  { name = "*.pef", fg = "#d33682" },
  { name = "*.pgm", fg = "#d33682" },
  { name = "*.php", fg = "#839496" },
  { name = "*.pid", fg = "#586e75" },
  { name = "*.pkg", fg = "#dc322f", bold = true },
  { name = "*.png", fg = "#d33682" },
  { name = "*.pod", fg = "#839496" },
  { name = "*.ppm", fg = "#d33682" },
  { name = "*.pps", fg = "#cb4b16" },
  { name = "*.ppt", fg = "#cb4b16" },
  { name = "*.pro", fg = "#839496" },
  { name = "*.ps1", fg = "#839496" },
  { name = "*.psd", fg = "#d33682" },
  { name = "*.ptx", fg = "#d33682" },
  { name = "*.pxn", fg = "#d33682" },
  { name = "*.pyc", fg = "#586e75" },
  { name = "*.pyd", fg = "#586e75" },
  { name = "*.pyo", fg = "#586e75" },
  { name = "*.qoi", fg = "#d33682" },
  { name = "*.r3d", fg = "#d33682" },
  { name = "*.raf", fg = "#d33682" },
  { name = "*.rar", fg = "#dc322f", bold = true },
  { name = "*.raw", fg = "#d33682" },
  { name = "*.rpm", fg = "#dc322f", bold = true },
  { name = "*.rst", fg = "#839496" },
  { name = "*.rtf", fg = "#cb4b16" },
  { name = "*.rw2", fg = "#d33682" },
  { name = "*.rwl", fg = "#d33682" },
  { name = "*.rwz", fg = "#d33682" },
  { name = "*.sbt", fg = "#839496" },
  { name = "*.sql", fg = "#839496" },
  { name = "*.sr2", fg = "#d33682" },
  { name = "*.srf", fg = "#d33682" },
  { name = "*.srw", fg = "#d33682" },
  { name = "*.stl", fg = "#d33682" },
  { name = "*.stp", fg = "#d33682" },
  { name = "*.sty", fg = "#586e75" },
  { name = "*.svg", fg = "#d33682" },
  { name = "*.swf", fg = "#d33682", bold = true },
  { name = "*.swp", fg = "#586e75" },
  { name = "*.sxi", fg = "#cb4b16" },
  { name = "*.sxw", fg = "#cb4b16" },
  { name = "*.tar", fg = "#dc322f", bold = true },
  { name = "*.tbz", fg = "#dc322f", bold = true },
  { name = "*.tcl", fg = "#839496" },
  { name = "*.tex", fg = "#839496" },
  { name = "*.tga", fg = "#d33682" },
  { name = "*.tgz", fg = "#dc322f", bold = true },
  { name = "*.tif", fg = "#d33682" },
  { name = "*.tml", fg = "#839496" },
  { name = "*.tmp", fg = "#586e75" },
  { name = "*.toc", fg = "#586e75" },
  { name = "*.tsx", fg = "#839496" },
  { name = "*.ttf", fg = "#6c71c4" },
  { name = "*.txt", fg = "#839496" },
  { name = "*.typ", fg = "#839496" },
  { name = "*.usd", fg = "#d33682" },
  { name = "*.vcd", fg = "#dc322f", bold = true },
  { name = "*.vim", fg = "#839496" },
  { name = "*.vob", fg = "#d33682", bold = true },
  { name = "*.vsh", fg = "#839496" },
  { name = "*.wav", fg = "#2aa198" },
  { name = "*.wma", fg = "#2aa198" },
  { name = "*.wmv", fg = "#d33682", bold = true },
  { name = "*.wrl", fg = "#d33682" },
  { name = "*.x3d", fg = "#d33682" },
  { name = "*.x3f", fg = "#d33682" },
  { name = "*.xlr", fg = "#cb4b16" },
  { name = "*.xls", fg = "#cb4b16" },
  { name = "*.xml", fg = "#839496" },
  { name = "*.xmp", fg = "#839496" },
  { name = "*.xpm", fg = "#d33682" },
  { name = "*.xvf", fg = "#d33682" },
  { name = "*.yml", fg = "#839496" },
  { name = "*.zig", fg = "#839496" },
  { name = "*.zip", fg = "#dc322f", bold = true },
  { name = "*.zsh", fg = "#839496" },
  { name = "*.zst", fg = "#dc322f", bold = true },
  { name = "*TODO", fg = "#839496", bold = true },
  { name = "*hgrc", fg = "#839496" },
  { name = "*.avif", fg = "#d33682" },
  { name = "*.bash", fg = "#839496" },
  { name = "*.braw", fg = "#d33682" },
  { name = "*.conf", fg = "#839496" },
  { name = "*.dart", fg = "#839496" },
  { name = "*.data", fg = "#d33682" },
  { name = "*.diff", fg = "#839496" },
  { name = "*.docx", fg = "#cb4b16" },
  { name = "*.epub", fg = "#cb4b16" },
  { name = "*.fish", fg = "#839496" },
  { name = "*.flac", fg = "#2aa198" },
  { name = "*.h264", fg = "#d33682", bold = true },
  { name = "*.hack", fg = "#839496" },
  { name = "*.heif", fg = "#d33682" },
  { name = "*.hgrc", fg = "#839496" },
  { name = "*.html", fg = "#839496" },
  { name = "*.iges", fg = "#d33682" },
  { name = "*.info", fg = "#839496" },
  { name = "*.java", fg = "#839496" },
  { name = "*.jpeg", fg = "#d33682" },
  { name = "*.json", fg = "#839496" },
  { name = "*.less", fg = "#839496" },
  { name = "*.lisp", fg = "#839496" },
  { name = "*.lock", fg = "#586e75" },
  { name = "*.make", fg = "#839496" },
  { name = "*.mojo", fg = "#839496" },
  { name = "*.mpeg", fg = "#d33682", bold = true },
  { name = "*.nims", fg = "#839496" },
  { name = "*.opus", fg = "#2aa198" },
  { name = "*.orig", fg = "#586e75" },
  { name = "*.pptx", fg = "#cb4b16" },
  { name = "*.prql", fg = "#839496" },
  { name = "*.psd1", fg = "#839496" },
  { name = "*.psm1", fg = "#839496" },
  { name = "*.purs", fg = "#839496" },
  { name = "*.raku", fg = "#839496" },
  { name = "*.rlib", fg = "#586e75" },
  { name = "*.sass", fg = "#839496" },
  { name = "*.scad", fg = "#839496" },
  { name = "*.scss", fg = "#839496" },
  { name = "*.step", fg = "#d33682" },
  { name = "*.tbz2", fg = "#dc322f", bold = true },
  { name = "*.tiff", fg = "#d33682" },
  { name = "*.toml", fg = "#839496" },
  { name = "*.usda", fg = "#d33682" },
  { name = "*.usdc", fg = "#d33682" },
  { name = "*.usdz", fg = "#d33682" },
  { name = "*.webm", fg = "#d33682", bold = true },
  { name = "*.webp", fg = "#d33682" },
  { name = "*.woff", fg = "#6c71c4" },
  { name = "*.xbps", fg = "#dc322f", bold = true },
  { name = "*.xlsx", fg = "#cb4b16" },
  { name = "*.yaml", fg = "#839496" },
  { name = "*stdin", fg = "#586e75" },
  { name = "*v.mod", fg = "#839496" },
  { name = "*.blend", fg = "#d33682" },
  { name = "*.cabal", fg = "#839496" },
  { name = "*.cache", fg = "#586e75" },
  { name = "*.class", fg = "#586e75" },
  { name = "*.cmake", fg = "#839496" },
  { name = "*.ctags", fg = "#586e75" },
  { name = "*.dylib", fg = "#839496" },
  { name = "*.dyn_o", fg = "#586e75" },
  { name = "*.gcode", fg = "#839496" },
  { name = "*.ipynb", fg = "#839496" },
  { name = "*.mdown", fg = "#839496" },
  { name = "*.patch", fg = "#839496" },
  { name = "*.rmeta", fg = "#586e75" },
  { name = "*.scala", fg = "#839496" },
  { name = "*.shtml", fg = "#839496" },
  { name = "*.swift", fg = "#839496" },
  { name = "*.toast", fg = "#dc322f", bold = true },
  { name = "*.woff2", fg = "#6c71c4" },
  { name = "*.xhtml", fg = "#839496" },
  { name = "*Icon\r", fg = "#586e75" },
  { name = "*LEGACY", fg = "#839496" },
  { name = "*NOTICE", fg = "#839496" },
  { name = "*README", fg = "#839496" },
  { name = "*go.mod", fg = "#839496" },
  { name = "*go.sum", fg = "#586e75" },
  { name = "*passwd", fg = "#839496" },
  { name = "*shadow", fg = "#839496" },
  { name = "*stderr", fg = "#586e75" },
  { name = "*stdout", fg = "#586e75" },
  { name = "*.bashrc", fg = "#839496" },
  { name = "*.config", fg = "#839496" },
  { name = "*.dyn_hi", fg = "#586e75" },
  { name = "*.flake8", fg = "#839496" },
  { name = "*.gradle", fg = "#839496" },
  { name = "*.groovy", fg = "#839496" },
  { name = "*.ignore", fg = "#839496" },
  { name = "*.matlab", fg = "#839496" },
  { name = "*.nimble", fg = "#839496" },
  { name = "*COPYING", fg = "#839496" },
  { name = "*INSTALL", fg = "#839496" },
  { name = "*LICENCE", fg = "#839496" },
  { name = "*LICENSE", fg = "#839496" },
  { name = "*TODO.md", fg = "#839496", bold = true },
  { name = "*VERSION", fg = "#839496" },
  { name = "*.alembic", fg = "#d33682" },
  { name = "*.desktop", fg = "#839496" },
  { name = "*.gemspec", fg = "#839496" },
  { name = "*.mailmap", fg = "#839496" },
  { name = "*Doxyfile", fg = "#839496" },
  { name = "*Makefile", fg = "#839496" },
  { name = "*TODO.txt", fg = "#839496", bold = true },
  { name = "*setup.py", fg = "#839496" },
  { name = "*.DS_Store", fg = "#586e75" },
  { name = "*.cmake.in", fg = "#839496" },
  { name = "*.fdignore", fg = "#839496" },
  { name = "*.kdevelop", fg = "#839496" },
  { name = "*.markdown", fg = "#839496" },
  { name = "*.rgignore", fg = "#839496" },
  { name = "*.tfignore", fg = "#839496" },
  { name = "*CHANGELOG", fg = "#839496" },
  { name = "*COPYRIGHT", fg = "#839496" },
  { name = "*README.md", fg = "#839496" },
  { name = "*bun.lockb", fg = "#586e75" },
  { name = "*configure", fg = "#839496" },
  { name = "*.gitconfig", fg = "#839496" },
  { name = "*.gitignore", fg = "#839496" },
  { name = "*.localized", fg = "#586e75" },
  { name = "*.scons_opt", fg = "#586e75" },
  { name = "*.timestamp", fg = "#586e75" },
  { name = "*CODEOWNERS", fg = "#839496" },
  { name = "*Dockerfile", fg = "#839496" },
  { name = "*INSTALL.md", fg = "#839496" },
  { name = "*README.txt", fg = "#839496" },
  { name = "*SConscript", fg = "#839496" },
  { name = "*SConstruct", fg = "#839496" },
  { name = "*.cirrus.yml", fg = "#839496" },
  { name = "*.gitmodules", fg = "#839496" },
  { name = "*.synctex.gz", fg = "#586e75" },
  { name = "*.travis.yml", fg = "#839496" },
  { name = "*INSTALL.txt", fg = "#839496" },
  { name = "*LICENSE-MIT", fg = "#839496" },
  { name = "*MANIFEST.in", fg = "#839496" },
  { name = "*Makefile.am", fg = "#839496" },
  { name = "*Makefile.in", fg = "#586e75" },
  { name = "*.applescript", fg = "#839496" },
  { name = "*.fdb_latexmk", fg = "#586e75" },
  { name = "*.webmanifest", fg = "#839496" },
  { name = "*CHANGELOG.md", fg = "#839496" },
  { name = "*CONTRIBUTING", fg = "#839496" },
  { name = "*CONTRIBUTORS", fg = "#839496" },
  { name = "*appveyor.yml", fg = "#839496" },
  { name = "*configure.ac", fg = "#839496" },
  { name = "*.bash_profile", fg = "#839496" },
  { name = "*.clang-format", fg = "#839496" },
  { name = "*.editorconfig", fg = "#839496" },
  { name = "*CHANGELOG.txt", fg = "#839496" },
  { name = "*.gitattributes", fg = "#839496" },
  { name = "*.gitlab-ci.yml", fg = "#839496" },
  { name = "*CMakeCache.txt", fg = "#586e75" },
  { name = "*CMakeLists.txt", fg = "#839496" },
  { name = "*LICENSE-APACHE", fg = "#839496" },
  { name = "*pyproject.toml", fg = "#839496" },
  { name = "*CODE_OF_CONDUCT", fg = "#839496" },
  { name = "*CONTRIBUTING.md", fg = "#839496" },
  { name = "*CONTRIBUTORS.md", fg = "#839496" },
  { name = "*.sconsign.dblite", fg = "#586e75" },
  { name = "*CONTRIBUTING.txt", fg = "#839496" },
  { name = "*CONTRIBUTORS.txt", fg = "#839496" },
  { name = "*requirements.txt", fg = "#839496" },
  { name = "*package-lock.json", fg = "#586e75" },
  { name = "*CODE_OF_CONDUCT.md", fg = "#839496" },
  { name = "*.CFUserTextEncoding", fg = "#586e75" },
  { name = "*CODE_OF_CONDUCT.txt", fg = "#839496" },
  { name = "*azure-pipelines.yml", fg = "#839496" },
]
