[mgr]
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 4
title_format = "yazi: {cwd}"

[preview]
tab_size = 4

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
